### ISSUE TITLE
k8s namespace missing

### ISSUE THREAD

**Issue by pulberg** [brujoand/sbp#108]
**Describe the bug**
I have the k8s segment enabled, but i don't see the namespace.

**To Reproduce**
1. enable k8s segment

**Expected behavior**
i should see all aspects of current k8s context

**Screenshots**
my current sbp prompt shows - 

![Screen Shot 2020-11-09 at 1 29 12 PM](https://user-images.githubusercontent.com/11069351/98587449-c70b3400-228f-11eb-9572-3bf69e4d7e9f.png)

k8s cluster - sandboxc
current namespace - nats

From my kube/config - 

```
current-context: sandboxc
- context:
        cluster: sandboxc
        namespace: nats
        user: sandboxc
  name: sandboxc

- name: sandboxc
   user:
        token: user:token
```

**Environment (please complete the following information):**
 - OS: MacOS 10.15.7
 - Terminal: iTerm2 
 - Version: v3.4.0beta13

**Additional context**
